export const USER = {
  DISPATCH_INFO_LOGIN: 'DISPATCH_INFO_LOGIN',
  GET_LOGIN_API: 'GET_LOGIN_API',
  LOGOUT_USER: 'LOGOUT_USER',
  LOGOUT_USER_ERROR: 'LOGOUT_USER_ERROR',
  UPDATE_INFO_USER_ACCESS_TOKEN: 'UPDATE_INFO_USER_ACCESS_TOKEN',
  PUT_CHANGE_PASSWORD: 'PUT_CHANGE_PASSWORD',
}
export const COMMON = {
  DISPATCH_LOADING_SCREEN: 'DISPATCH_LOADING_SCREEN',
  DISPATCH_RESET_STORE: 'DISPATCH_RESET_STORE',
}
