export const USER = {
  DISPATCH_INFO_LOGIN: 'DISPATCH_INFO_LOGIN',
  GET_LOGIN_API: 'GET_LOGIN_API',
  LOGOUT_USER: 'LOGOUT_USER',
  LOGOUT_USER_ERROR: 'LOGOUT_USER_ERROR',
  UPDATE_INFO_USER_ACCESS_TOKEN: 'UPDATE_INFO_USER_ACCESS_TOKEN',
  PUT_CHANGE_PASSWORD: 'PUT_CHANGE_PASSWORD',
}
export const COMMON = {
  DISPATCH_LOADING_SCREEN: 'DISPATCH_LOADING_SCREEN',
  DISPATCH_RESET_STORE: 'DISPATCH_RESET_STORE',
  DISPATCH_LIST_CATEGORY: 'DISPATCH_LIST_CATEGORY',
  GET_LIST_CATEGORY: 'GET_LIST_CATEGORY',
}
export const CATEGORY = {
  POST_INFO_CATEGORY: 'POST_INFO_CATEGORY',
  PUT_INFO_CATEGORY: 'PUT_INFO_CATEGORY',
  PUT_ACTIVE_CATEGORY: 'PUT_ACTIVE_CATEGORY',
}
export const TEAM = {
  POST_INFO_TEAM: 'POST_INFO_TEAM',
  PUT_INFO_TEAM: 'PUT_INFO_TEAM',
  PUT_ACTIVE_TEAM: 'PUT_ACTIVE_TEAM',
}
export const LEAGUE = {
  POST_INFO_LEAGUE: 'POST_INFO_LEAGUE',
  PUT_INFO_LEAGUE: 'PUT_INFO_LEAGUE',
  PUT_ACTIVE_LEAGUE: 'PUT_ACTIVE_LEAGUE',
}