export const USER = {
  DISPATCH_INFO_LOGIN: 'DISPATCH_INFO_LOGIN',
  GET_LOGIN_API: 'GET_LOGIN_API',
  LOGOUT_USER: 'LOGOUT_USER',
  LOGOUT_USER_ERROR: 'LOGOUT_USER_ERROR',
  UPDATE_INFO_USER_ACCESS_TOKEN: 'UPDATE_INFO_USER_ACCESS_TOKEN',
  PUT_CHANGE_PASSWORD: 'PUT_CHANGE_PASSWORD',
  GET_COMPANIES_FOR_USER: 'GET_COMPANIES_FOR_USER',
  DISPATCH_COMPANIES_FOR_USER: 'DISPATCH_COMPANIES_FOR_USER',
  GET_DEPARTMENTS_FOR_USER: 'GET_DEPARTMENTS_FOR_USER',
  DISPATCH_DEPARTMENTS_FOR_USER: 'DISPATCH_DEPARTMENTS_FOR_USER',
} as const

export const COMMON = {
  DISPATCH_LOADING_SCREEN: 'DISPATCH_LOADING_SCREEN',
  DISPATCH_RESET_STORE: 'DISPATCH_RESET_STORE',
  DISPATCH_LIST_CATEGORY: 'DISPATCH_LIST_CATEGORY',
  GET_LIST_CATEGORY: 'GET_LIST_CATEGORY',
  DISPATCH_LIST_TEAM: 'DISPATCH_LIST_TEAM',
  GET_LIST_TEAM: 'GET_LIST_TEAM',
  DISPATCH_LIST_TRANSACTION_TYPE: 'DISPATCH_LIST_TRANSACTION_TYPE',
  GET_LIST_TRANSACTION_TYPE: 'GET_LIST_TRANSACTION_TYPE',
} as const

export const CATEGORY = {
  POST_INFO_CATEGORY: 'POST_INFO_CATEGORY',
  PUT_INFO_CATEGORY: 'PUT_INFO_CATEGORY',
  PUT_TOGGLE_ACTIVE_CATEGORY: 'PUT_TOGGLE_ACTIVE_CATEGORY',
} as const

export const TEAM = {
  POST_INFO_TEAM: 'POST_INFO_TEAM',
  PUT_INFO_TEAM: 'PUT_INFO_TEAM',
  PUT_TOGGLE_ACTIVE_TEAM: 'PUT_TOGGLE_ACTIVE_TEAM',
} as const

export const LEAGUE = {
  POST_INFO_LEAGUE: 'POST_INFO_LEAGUE',
  PUT_INFO_LEAGUE: 'PUT_INFO_LEAGUE',
  PUT_TOGGLE_ACTIVE_LEAGUE: 'PUT_TOGGLE_ACTIVE_LEAGUE',
} as const

export const GAME = {
  POST_INFO_GAME: 'POST_INFO_GAME',
  PUT_INFO_GAME: 'PUT_INFO_GAME',
  PUT_TOGGLE_ACTIVE_GAME: 'PUT_TOGGLE_ACTIVE_GAME',
  PUT_MATCH_RESULT_GAME: 'PUT_MATCH_RESULT_GAME',
} as const

export const CUSTOMER = {
  PUT_TOGGLE_ACTIVE_CUSTOMER: 'PUT_TOGGLE_ACTIVE_CUSTOMER',
} as const

export const NHANVIEN = {
  GET_LIST_NHANVIEN: 'GET_LIST_NHANVIEN',
  DISPATCH_LIST_NHANVIEN: 'DISPATCH_LIST_NHANVIEN',
} as const
